### ISSUE TITLE
Update nr.nc to have dedicated list of arguments

### ISSUE THREAD

**Issue by gcasella** [dmulyalin/salt-nornir#11]
Continuation of our discussion on Slack;

When using the following `nr.nc rpc` command
>  salt 'nrp02' nr.nc rpc rpc="salt://templates/my_rpc.xml" FO='[{"hostname": "192.168.2.2"}]' 

This would provide an invalid response, the needed command to be run was providing the full string of `my_rpc.xml` in the cli.
> salt 'nrp02' [nr.nc](http://nr.nc/) rpc rpc="<get-firewall-filter-information><filtername>FILTER_NAME</filtername></get-firewall-filter-information>" FO='[{"hostname": "192.168.2.2"}]'

Adding the `render='["rpc"]'` argument at the end of the first command was successful 
Adding screenshot from slack for reference;
![image](https://user-images.githubusercontent.com/7719536/180482530-8151633d-cc26-44df-8f8e-ec91a9d0ec30.png)

**Comment by dmulyalin** [comment]
Hi, updated nr.nc function with its own render arguments list in latest commit https://github.com/dmulyalin/salt-nornir/commit/bee3e0becf01ed9a232b3fccff4f075d53d57449

**Comment by dmulyalin** [comment]
That was adressed starting with release 0.13.1
