### ISSUE TITLE
 nr_diagram 

### ISSUE THREAD

**Issue by arshaans** [dmulyalin/salt-nornir#13]
Unable to run nr.diagram with latest release 0.13.

[root@salt-master-3004 /]# salt nrp1 nr.diagram
nrp1:
    'nr.diagram' is not available.
ERROR: Minions returned with non-zero exit code

[root@salt-master-3004 /]# salt-run nr.diagram L2 v3d
'nr.diagram' is not available.

**Comment by dmulyalin** [comment]
Hello, please refer to sample usage section on how to call it - https://salt-nornir.readthedocs.io/en/latest/Nornir%20Runner%20Module.html#nr-diagram - in essence, need to use `salt-run` not `salt` app to call it as `nr.diagram` is a runner module not execution module.

**Comment by dmulyalin** [comment]
Let me know if any further help required, closing for now.
