### ISSUE TITLE
Add support for InfluxDB2 for sending metrics

### ISSUE THREAD

**Issue by abhi1693** [dmulyalin/salt-nornir#17]
We use InfluxDB2 in our organization and would like this plugin to send metrics data to the database.

Docs: https://docs.influxdata.com/influxdb/v2.3/
API Guide: https://docs.influxdata.com/influxdb/v2.3/api-guide/
Python Library: https://docs.influxdata.com/influxdb/v2.3/api-guide/client-libraries/python/

Note: The module in the salt repo for InfluxDB is for v1 which has now been discontinued.

**Comment by abhi1693** [comment]
InfluxData has another product called `Telegraf` which is usually used for collecting metrics. Maybe this can also be considered if it is easier.

https://docs.influxdata.com/telegraf/v1.23/

**Comment by dmulyalin** [comment]
Think the best way to approach this is to contribute to SaltStack by updating influxdb returner to latest supported version or b writing influxdb2 extension returner module that can be installed from PIP and loaded by SaltStack. 

Don't think I have much incentive and time to do it by myself at this stage, but I am happy to assist wherever I can.

**Comment by abhi1693** [comment]
I don't think I currently have the time cycle to do this myself, but I'll definitely open a Github issue with them later next week.
