### ISSUE TITLE
Fresh install with 0.3.0  proxy does not start . missing nornir.grains ?

### ISSUE THREAD

**Issue by network-shark** [dmulyalin/salt-nornir#2]
Hey @dmulyalin ,

 I created a new venv with the new version , but the minion does not start. 
```
╰─ pip list | egrep 'nornir|salt'
nornir                                            3.0.0
nornir-napalm                                     0.1.1
nornir-netmiko                                    0.1.1
nornir-salt                                       0.3.0
salt                                              3002.2
salt-nornir                                       0.3.0
```

Bad Trace from the minion startup 
https://pastebin.com/dVs5qEa2

Created a fresh venv with 0.2.2 , minions starts fine 
```
╰─  pip list | egrep 'nornir|salt'
nornir                                            3.0.0
nornir-napalm                                     0.1.1
nornir-netmiko                                    0.1.1
nornir-salt                                       0.3.0
salt                                              3002.2
salt-nornir                                       0.2.2
```

Good Trace https://pastebin.com/1vpmxy73  from the minion startup 

best regards, sharky

**Comment by dmulyalin** [comment]
Thank you for doing this testing. What is the OS you doing this installations on - Ubuntu, CentOS?

**Comment by network-shark** [comment]
Big Sur 

Python 3.6.8 (default, Nov  8 2019, 21:16:45)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by dmulyalin** [comment]
Probalem with nornir_salt package, function ToFile added recently and does not exist in nornir_salt v 0.3.0, as a result salt_nornir fails to import and start. Updated packages and published new versions.

To fix try:

    python3 -m pip install nornir_salt --upgrade

that would install required version and nornir proxy should start

**Comment by network-shark** [comment]
Update 

```
╰─ pip list | grep nornir
nornir                                            3.0.0
nornir-napalm                                     0.1.1
nornir-netmiko                                    0.1.1
nornir-salt                                       0.3.1
salt-nornir                                       0.3.0

Trying to execute

```
salt nrp1 nr.task "nornir_netmiko.tasks.netmiko.netmiko_send_command" command_string="show ip arp" use_textfsm=True FB="IOL1"
```

```
nrp1:
    Nornir-proxy MAIN PID 88127 job failed: {'task_fun': 'nornir_netmiko.tasks.netmiko.netmiko_send_command', 'args': (), 'kwargs': {'command_string': 'show ip arp', 'use_textfsm': True, 'FB': 'IOL1', '__pub_fun': 'nr.task', '__pub_arg': ['nornir_netmiko.tasks.netmiko.netmiko_send_command', {'command_string': 'show ip arp', 'use_textfsm': True, 'FB': 'IOL1'}], '__pub_tgt': 'nrp1', '__pub_jid': '20210218161558545483', '__pub_ret': '', '__pub_master_id': 'master_of_minons', '__pub_tgt_type': 'glob', '__pub_user': 'sharky'}, 'pid': 89233, 'name': 'nornir_netmiko.tasks.netmiko.netmiko_send_command', 'add_details': False}, child PID 89233, error:
    'Traceback (most recent call last):
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt_nornir/lib/python3.6/site-packages/salt_nornir/proxy/nornir_proxy_module.py", line 763, in _worker
        task_fun = _get_or_import_task_fun(job["task_fun"])
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt_nornir/lib/python3.6/site-packages/salt_nornir/proxy/nornir_proxy_module.py", line 631, in _get_or_import_task_fun
        module = __import__(plugin, fromlist=[""])
    ModuleNotFoundError: No module named 'nornir_netmiko.tasks.netmiko'
    '
```

```

**Comment by dmulyalin** [comment]
Internally `nornir_netmiko.tasks.netmiko.netmiko_send_command` translated to `from nornir_netmiko.tasks.netmiko import netmiko_send_command`, but that import string might not be completely right, hence import fails - `ModuleNotFoundError`. Have a look at [example ](https://salt-nornir.readthedocs.io/en/latest/Examples.html#calling-task-plugins-using-nr-task) in docs.

Try: 
`salt nrp1 nr.task "nornir_netmiko.tasks.netmiko_send_command" command_string="show ip arp" use_textfsm=True FB="IOL1"`

However, above should be equivalent to:

`salt nrp1 nr.cli "show ip arp" netmiko_kwargs='{"use_textfsm": True}' FB="IOL1"`

**Comment by network-shark** [comment]
Yep , it works thank you !

**Comment by dmulyalin** [comment]
great, thanks one more time for doing testing, feel free to raise another issue if encounter more problems.
