### ISSUE TITLE
import extended napalm drivers

### ISSUE THREAD

**Issue by davama** [dmulyalin/salt-nornir#23]
Hello,

I am playing around with salt-nornir and it’s awesome! Ive been using plain nornir with my extended drivers for a few months now and wanted to try salt.

I understand that i can call napalm getters using the nornir_napalm…napalm_get task:

```
salt minion nr.task nornir_napalm.plugins.tasks.napalm_get getters='["get_facts"]' FG="procurve" FB="h-txa-*"
```

i have no issues with the above. 

with plain nornir and having my extended drivers in my working directory under `custom_napalm/driverbla.py` i can easily call an extended function as so:

```
# where get_facts_custom is my extended function 
results = devices.run(task=napalm_get, getters=["get_facts", "get_facts_custom", "get_environment"])
```

Was trying to see if just by placing `custon_napalm` folder somewhere was enough for napalm to inherit it as shown here:  https://github.com/napalm-automation/napalm/blob/d978c3db886f12d2b83938da63676adfcc16431b/napalm/base/__init__.py#L77

On the salt-master ive tried under`/root/` (since salt is running as root), under `/etc/salt` (just a guess), and even tried `/var/run/salt`.

Is what im trying to do even possible?
Any suggestions?

I also have a custom nornir task we use, similar to `nornir_napalm.plugins.tasks.napalm_get` but one challenge at a time 😄

Any input is much appreciated!

Thank you for this amazing project!

Best,
Dave

**Comment by davama** [comment]
Got my hopes up when i tried the `provider: custom_napalm_base` as shown here but no beans :( 

https://docs.saltproject.io/en/latest/ref/proxy/all/salt.proxy.napalm.html

**Comment by dmulyalin** [comment]
For custom function can create a file on salt master with task content and place it say at `/etc/salt/tasks/my_task.py`, can call that task from salt-nornir `salt nrp1 nr.task plugin="salt://tasks/my_task.py"`, [docs](https://salt-nornir.readthedocs.io/en/latest/Nornir%20Execution%20Module.html#nr-task) for details 

Regarding custom_module, try creating folder under python site-packages on machine where proxy-minion process is running, for example:

`/usr/local/lib/python3.9/site-packages/custom_napalm/my_custom_module/module_filename.py`

within `module_filename.py` need to have custom driver class which is subcalss of NetworkDriver object.

Next, try using this in your Salt-Nornir inventory:
```
hosts:
  my_host:
    connection_options:
      napalm:
        platform: "custom_napalm.my_custom_module.module_filename"
```
would expect above should work and custom NAPALM driver will be loaded for given host.

You can also test that your custom module import works by using importlib:
```
import importlib

module = import.import_module("custom_napalm.my_custom_module.module_filename")
```
as per this [code](https://github.com/napalm-automation/napalm/blob/d978c3db886f12d2b83938da63676adfcc16431b/napalm/base/__init__.py#L88)

**Comment by davama** [comment]
Thank you for the reply @dmulyalin 

I like your idea and ended up doing this on my `docker-compose.yaml` file:

```
      - ./custom_napalm:/usr/local/lib/python3.9/site-packages/custom_napalm
      - ./custom_nornir_napalm/napalm_custom.py:/usr/local/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_custom.py
```

My `napalm_custom.py` is simply a clone of `napalm_get.py` but instead of being able to run napalm `get_bla` functions, it will run `custom_bla`. All works as expected. And i did not have to update my pillar file with a custom `platform`

Using extended napalm functions :+1: 

```
salt usa-ht nr.task nornir_napalm.plugins.tasks.napalm_get getters='["get_facts_custom"]' FO='{"serial":"12323425"}'
usa-ht:
    ----------
    usa-nyhsq-b1s-sw-1:
        ----------
        nornir_napalm.plugins.tasks.napalm_get:
            ----------
            get_facts_custom:
                ----------
                base_mac_address:
                    a4:56:30:b5:85:52
                fqdn:
                    Unknown
                hostname:
                    bla-sw-1
                interface_list:
                    - FastEthernet1
                   ...
                model:
                    SRW224G4P-K9
                model_number:
                    SF300-24P
                os_version:
                    1.3.7.18
                serial_number:
                    1234123
                snmp_location:
                    ACCESS
                uptime:
                    25129694
                vendor:
                    Cisco

```

Using the custom nornir_task :+1: 

```
salt usa-ht nr.task nornir_napalm.plugins.tasks.napalm_custom customs='["custom_copy_run_start"]' FO='{"serial":"12313423"}'
usa-ht:
    ----------
    bla-sw-1:
        ----------
        nornir_napalm.plugins.tasks.napalm_custom:
            ----------
            custom_copy_run_start:
                Copy succeeded
```

**Comment by davama** [comment]
@dmulyalin 

Do you think it would help future people to add this to the documentation? (how to use their extended napalm driver in salt-nornir)
