### ISSUE TITLE
[FEATURE REQUEST] salt-nornir nr.inventory update_defaults

### ISSUE THREAD

**Issue by bodleytunes** [dmulyalin/salt-nornir#28]
Hi

Something similar to the update_host functionality would also be useful to update the defaults section of the inventory.

e.g.

salt nrp1 nr.nornir inventory update_defaults data='{"username": "my_new_username", "password": "my_new_password123"}'

Which would be useful for updating things like global usernames and passwords in the inventory aswell as other things.

Thanks,

Jon.

**Comment by dmulyalin** [comment]
Added support for update defaults in 0.19.1:
```
salt nrp1 nr.nornir inventory update_defaults \
username=foo password=bar data='{"foo": "bar"}' \
port=1234 platform=foobar
```

**Comment by bodleytunes** [comment]
Nice! :)

**Comment by dmulyalin** [comment]
Hi @bodleytunes in latest nornir-salt commit [557fa5ab50b6590fbaededc25a6979e901cf4b5a ](https://github.com/dmulyalin/nornir-salt/commit/557fa5ab50b6590fbaededc25a6979e901cf4b5a) added support to set password, port, username and platform values to None
