### ISSUE TITLE
Use external pillar for inventory 

### ISSUE THREAD

**Issue by abhi1693** [dmulyalin/salt-nornir#5]
Is there a way that I can use my custom pillar which pulls data from netbox to feed it into nornir?

**Comment by dmulyalin** [comment]
As long as pillar returns data in salt nornir compatible format would expect it to work with no issues. On how to do it - might customuze your custom pillar to produce required structure?

**Comment by dmulyalin** [comment]
Here is a link for writing salt stack external pillars https://docs.saltproject.io/en/latest/topics/development/modules/external_pillars.html

**Comment by abhi1693** [comment]
This is an awesome library. Everything worked so far. I'll play with the library more and see how more I can do with it
