### ISSUE TITLE
How to get failed status while running commands

### ISSUE THREAD

**Issue by abhi1693** [dmulyalin/salt-nornir#6]
I have been trying to figure out if there is a way to know whether the result I received is a success or false, but it's not evident from the response. Am I missing anything with the configuration? I have only done the configuration exactly as per the getting started guide

```json
{
  "return":[
    {
      "home":{
        "home-csr1":{
          "nornir_salt.plugins.tasks.netmiko_send_commands":"nornir_salt:RetryRunner home-csr1 - connection netmiko, retry attempt 3, error: 'TCP connection to device failed.\n\nCommon causes of this problem are:\n1. Incorrect hostname or IP address.\n2. Wrong TCP port.\n3. Intermediate firewall blocking access.\n\nDevice settings: cisco_xe 172.16.14.54:22\n\n'"
        }
      }
    }
  ]
}
```

**Comment by dmulyalin** [comment]
You can manipulate results structure using to_dict arguments https://salt-nornir.readthedocs.io/en/latest/Nornir%20Execution%20Module.html#to-dict, e.g. set add_details=True will give you the status you or command execution

**Comment by abhi1693** [comment]
This worked as expected, thanks.
